name: pbj
channels:
  - conda-forge
  - defaults
  - eumetsat
dependencies:
  - python=3.14
  - fftw
  - jupyter
  - llvmlite
  - matplotlib
  - numpy
  - numba
  - ocl-icd
  - openblas
  - pdb2pqr
  - pip
  - plotly
 # - pocl
  - intel-opencl-rt
  - pybind11
  - pyopencl
  - scipy
  - tbb
  - fenics-dolfinx
  - mpich
  - pyvista
  - pip:
    - bempp-cl
    - meshio
    - gmsh
    - trimesh
    - pytest
    - rtree
    - kaleido
    - "git+https://github.com/exafmm/exafmm-t.git"
    - "git+https://github.com/bem4solvation/pbj.git@update_libs"
